# Generated by Django 5.1.15 on 2026-08-31 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initial_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at_round', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_rounds', models.PositiveIntegerField(default=4)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('WHITE_WIN', 'White win'), ('BLACK_WIN', 'Black win'), ('DRAW', 'Draw'), ('BYE', 'Bye'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('bye_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bye_pairings', to='tournaments.player')),
                ('player_black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_pairings', to='tournaments.player')),
                ('player_white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_pairings', to='tournaments.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='tournaments.round')),
            ],
            options={
                'ordering': ['round__round_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('tournament', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('tournament', 'name')},
        ),
    ]
