# Generated by Django 5.1.15 on 2026-08-31 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='is_forfeit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_rounds',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
