# Generated by Django 5.1.15 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_pairing_is_forfeit_alter_tournament_num_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='workspace_key',
            field=models.CharField(db_index=True, default='', max_length=40),
            preserve_default=False,
        ),
    ]