# Generated by Django 5.1.15 on 2026-08-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_workspace_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
