# Generated by Django 5.1.15 on 2026-09-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_end_time_tournament_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
